apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: jenkins-master
 namespace: jenkins
spec:
 revisionHistoryLimit: 2
 replicas: 1
 selector:
  matchLabels:
    app: jenkins-master
 template:
  metadata:
   labels:
    app: jenkins-master
   annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  spec:
   serviceAccountName: jenkins-service-account
   containers:
   - name: master
     image: 'jenkins/jenkins:2.168-alpine'
     securityContext:
       allowPrivilegeEscalation: false
     ports:
     - containerPort: 8080
     - containerPort: 50000
     readinessProbe:
      httpGet:
       path: /login
       port: 8080
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 2
      failureThreshold: 5
     volumeMounts:
     - mountPath: /var/jenkins_home
       name: jenkins-home
     resources:
      limits:
       cpu: 500m
       memory: 1500Mi
      requests:
       cpu: 500m
       memory: 1500Mi
   volumes:
   - name: jenkins-home
     persistentVolumeClaim:
      claimName: jenkins
