apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "jenkins-master"
  namespace: "jenkins"
  labels:
    name: "jenkins-master"
spec:
  serviceName: 'jenkins-master'
  replicas: 1
  selector:
    matchLabels:
      app: 'jenkins-master'
  volumeClaimTemplates:
    - metadata:
        name: "jenkins"
        namespace: "jenkins"
      spec:
        storageClassName: premium
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  template:
   metadata:
    labels:
     app: 'jenkins-master'
    annotations:
     seccomp.security.alpha.kubernetes.io/pod: docker/default
   spec:
    serviceAccountName: jenkins-service-account
    initContainers:
    - name: volume-mount-hack
      image: busybox
      command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
      volumeMounts:
      - mountPath: /var/jenkins_home
        subPath: data
        name: jenkins
    containers:
    - name: master
      image: 'cloudbees/cloudbees-jenkins-distribution:2.190.3.2'
      securityContext:
        allowPrivilegeEscalation: false
      ports:
      - containerPort: 8080
      - containerPort: 50000
      readinessProbe:
       httpGet:
        path: /login
        port: 8080
       periodSeconds: 10
       timeoutSeconds: 5
       successThreshold: 2
       failureThreshold: 5
      volumeMounts:
      - mountPath: /var/jenkins_home
        subPath: data
        name: jenkins
      resources:
       limits:
        cpu: "1"
        memory: 3000Mi
       requests:
        cpu: "1"
        memory: 3000Mi
      env:
      - name: JENKINS_HOME
        value: /var/jenkins_home
      - name: JAVA_OPTS
        value: -Dhudson.TcpSlaveAgentListener.hostName=jenkins-master -Dhudson.TcpSlaveAgentListener.port=50000 -Dhudson.DNSMultiCast.disabled=true -Djenkins.CLI.disabled=true
