version: "3.3"

services:
  jenkins:
    image: jenkins/jenkins:2.168-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.platform.os == linux'
      labels:
        com.docker.lb.hosts: "jenkins.az.olly.dtcntr.net"
        com.docker.lb.network: jenkins
        com.docker.lb.port: 8080
    networks:
        - jenkins
    ports:
        - 30000:8080
        - 50000:50000
    volumes:
        - jenkins:/var/jenkins_home
volumes:
  jenkins:

networks:
  jenkins:
    external: true
